### ISSUE TITLE
Epiforecast model updated

### ISSUE THREAD

**Issue by seabbs** [KITmetricslab/hospitalization-nowcast-hub#194]
As of the 6th the Epiforecast model has been updated with a day of the week effect for date of positive test.

Updated metadata: https://github.com/epiforecasts/eval-germany-sp-nowcasting/blob/main/data/nowcasts/submission/independent/metadata-epiforecasts-independent.txt
News update: https://github.com/epiforecasts/eval-germany-sp-nowcasting/blob/main/NEWS.md#2021-12-06
Evaluation (seeing a 10% improvement in performance for both relative and absolute measures with only a slight decrease in performance for 5 - 14 year olds): https://epiforecasts.io/eval-germany-sp-nowcasting/real-time/

Will be monitoring to assess if this is a long-term change or for now as may have unexpected downsides.

**Comment by jbracher** [comment]
Thanks, I updated the metadata file :+1:
